name: Sync Upstream

on:
  schedule:
    - cron: "*/60 * * * *"   # alle 10 Minuten
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"

      - run: |
          git remote add upstream https://github.com/odoo/odoo.git
          git fetch upstream
          git checkout 19.0
          git merge upstream/19.0 --no-edit || true

      - run: git push origin 19.0
